# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackathon 3.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hackathon 3.0
    pod 'SwiftSocket'

  target 'Hackathon 3.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hackathon 3.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
